### ISSUE TITLE
GermaNet resources

### ISSUE THREAD

**Issue by ghost** [wroberts/pygermanet#2]
What exactly do you download to get GermaNet resources? Could you provide a link or a more detailed description?

**Comment by wroberts** [comment]
Hi @Sadik thanks for the message.  The GermaNet homepage is 
   http://www.sfs.uni-tuebingen.de/GermaNet/
This is linked in the README.rst file, but I've added a few more links now to make it hopefully easier to find.  GermaNet is free for academic use, but you need to download and sign a license, and send it back to the University of Tuebingen.  In practice, it can take a little while before you're sent the download key.  GermaNet is distributed as a ZIP file which contains the data in two formats (SQL database dump and a set of XML files); pygermanet uses the XML portion of this data.  I hope this helps; please let me know if you have any difficulties to do with download and install.

**Comment by ghost** [comment]
Thank you!
