### ISSUE TITLE
Server Selection Timeout Error when loading

### ISSUE THREAD

**Issue by morethanbooks** [wroberts/pygermanet#3]
Hi there! I am trying to work for the first time with this tool. When I try to load it, I get a ServerSelectionTimeoutError. Here you should be able to see the problem.
![grafik](https://user-images.githubusercontent.com/5383381/132627202-5078a002-840e-4fb0-8e1a-792b98af4f89.png)

If I understand this correctly, the server from where I am trying to retrieve the data is not responding.

**Comment by wroberts** [comment]
Hi there, thanks for the ticket.

The server mentioned here is MongoDB, a database that pygermanet uses to store the germanet data.  As mentioned in the [readme](https://github.com/wroberts/pygermanet#setup), you'll need to get this working before you can use pygermanet.  You'll also need a copy of the GermaNet lexicon from Uni Tübingen, and you'll need to import this into MongoDB yourself with pygermanet's import script.  If you are able to import the GN data, you should also have no trouble retrieving it in Python.

I'm sorry that I'm not able to help very much with this, getting databases working can be a bit tricky.

**Comment by morethanbooks** [comment]
Ok, thanks for the explanation, and sorry for my delayed answer! Regards!
